### ISSUE TITLE
Annotations shell error reporting could be improved.

### ISSUE THREAD

**Issue by ADmad** [dereuromark/cakephp-ide-helper#10]
## What I did
Ran `bin/cake annotations controller -d -v`   (mistakenly used "controller" instead of "controllers")

## What I got
`Error: Unknown short option 'd'`

## What I expected
Something similar to `Error: Unknown option 'controller'`.

**Comment by dereuromark** [comment]
Isn't that part of the ConsoleOptionParser logic? Not sure how much influence each shell has here on the parsing of those arguments and options.

**Comment by dereuromark** [comment]
Personally I think that it would be nice to even have partial matching like the Symfony shells have.
There you can match

    console foo:bar:baz

as

    console f:b:b

etc, as long as you dont have conflicts.
But that is something for Cake4.0

**Comment by ADmad** [comment]
> Isn't that part of the ConsoleOptionParser logic?

Probably, I haven't dug into `ConsoleOptionParser`. If that's the case this ticket can be closed :)

**Comment by dereuromark** [comment]
Yeah, the come from the framework itself. Not much we can do here probably.
