### ISSUE TITLE
Test new phpstorm meta 

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-ide-helper#114]
https://blog.jetbrains.com/phpstorm/2019/02/new-phpstorm-meta-php-features/

see e.g.
https://github.com/JetBrains/phpstorm-stubs/blob/master/meta/.phpstorm.meta.php

I tested with phpstorm 2019.01 alpha and it didnt work (yet).
Maybe I did sth wrong.

**Comment by dereuromark** [comment]
Anyone has insights or wants to help out?

**Comment by dereuromark** [comment]
PHPSTORM 2019.2 is now released stable, we should look into this now.

**Comment by ndm2** [comment]
https://youtrack.jetbrains.com/issue/WI-45623

Well f*** me sideways. But it's only 5 been months yet, so....

**Comment by ndm2** [comment]
More to vote on:

* https://youtrack.jetbrains.com/issue/WI-45741
* https://youtrack.jetbrains.com/issue/WI-46047
* https://youtrack.jetbrains.com/issue/WI-45908
* https://youtrack.jetbrains.com/issue/WI-45823
* https://youtrack.jetbrains.com/issue/WI-45685

**Comment by ndm2** [comment]
Suddenly... progress.

> State:  Open ⟶ Fixed

`expectedArguments()` and `expectedReturnValues()` work quite nicely, even though there's quite a few rough edges.

I guess there's lots of stuff that IDE helper could possibly decorate, like, everything that accepts and/or returns constants, maybe assets for use with `HtmlHelper::css()/script()/image()`, domains for `__d*()` functions, event names for `EventManager::on()/off()`, methods that accept configuration keys, etc...

That's not me saying that I do have time to implement that though :wink:

**Comment by dereuromark** [comment]
Appreciate the feedback :) Maybe someone has a bit of spare time to help us out here.

**Comment by dereuromark** [comment]
Anyone interested in exploring some of those improvements?

**Comment by dereuromark** [comment]
The tests I did around https://github.com/dereuromark/cakephp-ide-helper/pull/148 look like promising.
For all those arguments, the expectedArguments() method is the right way to go, those dont work with override().
