### ISSUE TITLE
Illuminator a bit more descriptive on fields/associations

### ISSUE THREAD

**Issue by challgren** [dereuromark/cakephp-ide-helper#115]
It would be nice if Illuminator did FIELD_XXX for true and actual fields and FIELD_ASSOC_XXX for associations. That way an association couldn't be confused for a real field.

**Comment by dereuromark** [comment]
what about virtual fields? from entity Perspektive those are all equal somewhat

**Comment by challgren** [comment]
Those too

**Comment by dereuromark** [comment]
what if a real field is called virtuel_xxx?

**Comment by dereuromark** [comment]
I had the similar idea of separating:

- F_X for real fields
- V_X for virtual fields
- A_X for associations etc

but then I thought this to be so much overhead (needs then Model=>Entity handling and schema parsing as the annotator does) instead of just using the existing annotations of the Entity.

**Comment by dereuromark** [comment]
I think there are probably bigger fish to fry at this point.
