### ISSUE TITLE
PhpStorm: Jump between files

### ISSUE THREAD

**Issue by BassemN** [dereuromark/cakephp-ide-helper#121]
Hello,

Thanks a lot for your great plugin :+1:

Does your plugin allow jumping between the .ctp files on PhpStorm for example by clicking on the element name on the code like this `<?= $this->element('myElement'); ?>` then it opens the `myElement.ctp` file? if yes, how can I enable it?

Thanks

**Comment by dereuromark** [comment]
Please see https://github.com/dereuromark/cakephp-whoops#editor for whoops to use.
Or see if the core itself can be enabled here using similar ways.

But this is not in the scope of this plugin :)

**Comment by BassemN** [comment]
@dereuromark thanks a lot. I'll check this plugin.
