### ISSUE TITLE
$modelClass = false not respected in plugin controllers

### ISSUE THREAD

**Issue by dakota** [dereuromark/cakephp-ide-helper#128]
Given the below plugin controller

```
<?php

namespace Plugin\Controller;

use Cake\Controller\Controller;

/**
 * Class NoModelController
 */
class NoModelController extends Controller
{
    public $modelClass = false;
}

```

The annotator adds an incorrect `@property \Cake\ORM\Table $NoModel` annotation. This does not affect `App` controllers, only those in plugins.

**Comment by dereuromark** [comment]
Interesting, the $modelClass false should prevent this..

**Comment by dakota** [comment]
It does for non-plugin controllers, but not for plugin ones.

**Comment by dereuromark** [comment]
Do you see any difference here in code that warrants this change in behavior?

**Comment by dakota** [comment]
It looks like it's this block https://github.com/dereuromark/cakephp-ide-helper/blob/master/src/Annotator/ControllerAnnotator.php#L274-L284

**Comment by dereuromark** [comment]
Darn, thx, I will fix it.

**Comment by dereuromark** [comment]
Actually, this looks like a CORE bug:

    $modelClass = $controller->modelClass; // line 269

This returns the "guessed" model class, even though I also had


	/**
	 * @var string|bool
	 */
	public $modelClass = false;

In there
Could also be a regression of sorts here, but sure a CORE issue at this point.

**Comment by dereuromark** [comment]
Can you confirm that https://github.com/dereuromark/cakephp-ide-helper/pull/129 at least solves it for now?

**Comment by dereuromark** [comment]
I added a PR for core 3.next to fix it based on the already fixed 4.x core ( https://github.com/cakephp/cakephp/pull/13320 ).

**Comment by dakota** [comment]
If anything, #129 made it worse 😱 Now all plugin models are converted to `\Cake\ORM\Table`. I think I know the cause, will quickly check.

**Comment by dereuromark** [comment]
PR open: https://github.com/dereuromark/cakephp-ide-helper/pull/130
