### ISSUE TITLE
Works in Visual Studio Code and a beginner question

### ISSUE THREAD

**Issue by MrTucks** [dereuromark/cakephp-ide-helper#131]
Just wanted to report that it works in Visual Studio Code with the [Intelephense Extension](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client). Without this extension (with only the built-in basic PHP code completion) it doesn't work.

Also, I'm still a PHP beginner and completely new to CakePHP (completed the tutorial last week), so I would like someone to please confirm if this is the/a correct way to load the plugin in src/Application.php. Or could you please provide an example in the readme "Setup" section?
```
if(Configure::read('debug')){
    $this->addPlugin('IdeHelper');
}
```

And thank you so much for this plugin! Working code completion makes everything 1000 times easier and more fun. :)

**Comment by MrTucks** [comment]
I'm not sure if every feature works, because I don't know what all the code completion features are or if they work in other IDEs.
For example the following code doesn't get completed or suggested:
Dynamic finders,
I think no options arrays or other parameters that are strings work,
there is no code completion after a dynamic finder.

**Comment by saeideng** [comment]
this plugin just adds annotation to your application 
you need  to use one of extension like `Intelephense Extension` to enable/use code completion feature in VScode
this plugin can add annotation/meta data for dynamic things(finders , ....) but for now `Intelephense Extension` or other extensions can not use them yet
for `Intelephense` : https://github.com/bmewburn/vscode-intelephense/issues/471

**Comment by dereuromark** [comment]
Feel free to further improve/detail the https://github.com/dereuromark/cakephp-ide-helper/wiki/Visual-Studio-Code wiki page I created for this.
