### ISSUE TITLE
Auto collect view variables 

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-ide-helper#139]
We could auto collect undefined view variables and either keep the type missing or use mixed.

Issues to solve
- [x] prevent loop declared e.g. foreach (x as y) - y here
- [x] assignment detection via tokenizing?

side effects:
- [x] if above loop issue is solved we also have less wrongly added ones in other cases.

anyone up for trying?

**Comment by julianpollmann** [comment]
I'll give it a try, when there's time :)

**Comment by dereuromark** [comment]
For a more sophisticated approach one could also check out https://psalm.dev/articles/psalm-3-and-a-half and how they did some parsing/type-detection.

**Comment by dereuromark** [comment]
I added a demo to use existing token list: https://github.com/dereuromark/cakephp-ide-helper/compare/master-template-vars
I think if we do the following it should work:

- Find all T_VARIABLE and get the content and also store the index for later use
- Skip the ones that are in foreach ($x as $y => $z), in this case $y and $z - using nested_parenthesis={"a":b} data
- Try to skip the ones that are set in the template ($x = ...; echo $x;)

We could annotate those as mixed for now.
As a later step we could then also start guessing the type based on some info:
- `$var->` => object
- echo $var => string

More could be done later using a different strategy of reading the code (AST etc).

**Comment by dereuromark** [comment]
PR open: https://github.com/dereuromark/cakephp-ide-helper/pull/142

Do we want to have a blacklist of variable names not desired to be auto-collected? `_isSearch` or regex like `^_` (all underscore prefixed) as input possible?
