### ISSUE TITLE
Double annotations while baking

### ISSUE THREAD

**Issue by Theaxiom** [dereuromark/cakephp-ide-helper#14]
When I bake a new template (only on add/edit templates), I get this at the top in double:

```
<?php
/**
 * @var \App\View\AppView $this
 */
?>
<?php
/**
 * @var \App\View\AppView $this
 */
?>
```

**Comment by dereuromark** [comment]
Any idea why?

**Comment by Theaxiom** [comment]
I think I just figured it out, it was due to the fact those were added to my bake templates previously when I generated the annotations. :D

**Comment by dereuromark** [comment]
The newest Version should Blacklist those and Not modify bake templates. See the confiig for templates.

**Comment by Theaxiom** [comment]
Yeah, this was before that. I was the one who brought it to your attention. I am Xeus/trowland :)
