### ISSUE TITLE
virtual/@property-read ignored

### ISSUE THREAD

**Issue by raul338** [dereuromark/cakephp-ide-helper#140]
I have a [virtual property](https://book.cakephp.org/3.0/en/orm/entities.html#creating-virtual-fields) that is read only.
I added the `@property-read` and the annotator adds another `@property` with the same name

Example
```php
/**
 * Archivo Entity
 *
 * @property-read string $archivo
 *
 * Auto-annotated
 * @property string $archivo
 */
class Archivo extends Entity
{
    // ...
    /**
     * @return string Nombre original del Archivo
     */
    protected function _getArchivo()
    {
        return substr($this->nombre, 11);
    }
}
```

**Comment by dereuromark** [comment]
Technically, any property on the entity is always read+write.
In your case `->archivo = 'xyz'` would just be stored in a way that you cannot re-read it.
Basically so far everyone always used the normal `@property` tag here for simplicity.

But I can see the value of 
a) Detecting property-read and not re-adding a 2nd one
b) Maybe even managing the tags completely.

The latter is probably quite difficult as it would need to know if the mutator is modifying the property of the same name, or is a virtual one from different properties.

**Comment by dereuromark** [comment]
What's currently left is the functionality around modifying/updating existing ones if the type changes, and also removing outdated ones.
I think there is a bit more work needed - if anyone has some time to dig into that, would be awesome.

**Comment by dereuromark** [comment]
For this is solved pretty much to the extend you described. As such I think we can close for now.
