### ISSUE TITLE
Skipping table and entity: SQLSTATE[HY000] [2002]

### ISSUE THREAD

**Issue by king-fisher-berlin** [dereuromark/cakephp-ide-helper#15]
I'm receiving this message when doing:

`bin\cake annotations all -d -v`

``` Skipping table and entity: SQLSTATE[HY000] [2002] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.```

Why?

Best,
Mike

**Comment by dereuromark** [comment]
Sounds like it cannot connect to your DB. Are you sure you set up your Datasources correctly in your app.php?
Bake etc uses the same connection, so if bake works, if you can inside your app connect to your DB then this plugin can also work fine.
This is a user error, closing.

**Comment by king-fisher-berlin** [comment]
Stupid me. Sorry, for that, I just found the same and wanted to remove the request, but you were faster.
(Unusual not having the mysql service running.)
