### ISSUE TITLE
`float` incorrectly detected as `string` (Postgres, CakePHP 4)

### ISSUE THREAD

**Issue by swiffer** [dereuromark/cakephp-ide-helper#161]
my floats are now falsely annotated as string (when running v1.0 in CakePHP 4.0)

**Comment by dereuromark** [comment]
Is it really float, or type decimal? The latter are actually strings inside Cake4 now.

**Comment by swiffer** [comment]
Oh, yepp - as mentioned in the Migration Guide. Sorry, closing this one
