### ISSUE TITLE
hasOne relation can be null

### ISSUE THREAD

**Issue by raul338** [dereuromark/cakephp-ide-helper#162]
`Users` table hasOne `InfoUsers`
`InfoUsers` table belongsTo `Users` (since has user_id)

In `Model/Entity/User.php` the following annotation is generated
```php
* @property \App\Model\Entity\InfoUser $info_user
```
$info_user can be null, currently it annotates as always an object.

The annotation generated on InfoUsers is correct.

**Comment by dereuromark** [comment]
See https://github.com/cakephp/bake/issues/579 and the related IdeHelper PR
This is already fixed afaik.

**Comment by raul338** [comment]
Not in current release. It removes null from hasOne association
```bash
 ~/r/c/project   dev *+…  bin/cake annotations models                           4542ms  mié 08 ene 2020 13:45:33 -03
   -> 1 annotation updated.
 ~/r/c/project   dev *+…  git diff src/Model/Entity/Usuario.php                 2008ms  mié 08 ene 2020 13:45:47 -03
diff --git a/src/Model/Entity/Usuario.php b/src/Model/Entity/Usuario.php
index ab7ecfe..19b8aea 100644
--- a/src/Model/Entity/Usuario.php
+++ b/src/Model/Entity/Usuario.php
@@ -27,7 +27,7 @@ use Cake\Routing\Router;
  * @property string|null $url_foto
- * @property \App\Model\Entity\Tecnico|null $tecnico
+ * @property \App\Model\Entity\Tecnico $tecnico
  * @property bool $online
 ~/r/c/project   dev *+…  composer show | grep  cakephp-ide-helper           226ms  mié 08 ene 2020 13:46:39 -03
dereuromark/cakephp-ide-helper                 0.14.3  CakePHP IdeHelper Plugin to improve auto-completion
```

**Comment by dereuromark** [comment]
Then it is probably your DB schema doing this.
Is your DB field nullable (default null)? Otherwise it assumes this to be not nullable.

**Comment by raul338** [comment]
The column is on `InfoUsers` (`Tecnico` in my real use case), is `user_id` and is not null. It must be not null since a `InfoUser` cannot exists without a `User` (It doesn't make sense in my project)

**Comment by dereuromark** [comment]
But what is your DB schema for the users table? I would be interested in that.
The tool mainly aligns itself along the schema here.

As for your request of change:
Are you able to make a PR with your suggested changes?
That might make it more clear

**Comment by raul338** [comment]
Users: id, name, .....
InfoUser: id, user_id, description, .....

> Are you able to make a PR with your suggested changes?

I tried to peek at the code, the first idea I had is to differentiate hasOne and belongsTo (instead of ONE_TO_ONE type).
I will try tonight

**Comment by dereuromark** [comment]
I checked my code for ReleaseElementsTable
```php
$this->belongsTo('ReleaseGroups');
$this->hasOne('Releases');
```
gives me
```php
 * @property \App\Model\Entity\ReleaseGroup $release_group
 * @property \App\Model\Entity\Release|null $release
```

so exactly as you said.

Not sure why in your case this would behave differently.

Might be because it is optional here on the schema for releases table:
```php
'release_element_id' => ['type' => 'integer', 'length' => 11, 'null' => true, 'default' => null],
```

**Comment by dereuromark** [comment]
I opened https://github.com/dereuromark/cakephp-ide-helper/pull/163
You can PR against that one.

It shows the difference of nullable here
```php
 * @property \Relations\Model\Entity\Foo $foo
 * @property \Relations\Model\Entity\Bar|null $bar
```
https://github.com/dereuromark/cakephp-ide-helper/pull/163/files#diff-973234df6f90d2017898f693c8065f0eR9-R10

**Comment by dereuromark** [comment]
I agree that this is a bit weird, as the nullable part is for the belongsTo side, not for the hasOne, which is always `|null`.

**Comment by dereuromark** [comment]
Can you check if https://github.com/dereuromark/cakephp-ide-helper/pull/163/commits/9750848350b804199935e99b287989396e2b3dbe fixes it?

**Comment by raul338** [comment]
Yes! It kept the nullable typehint.

Thanks!
