### ISSUE TITLE
documentation update "annotate"

### ISSUE THREAD

**Issue by alexdd55** [dereuromark/cakephp-ide-helper#177]
In the documentation, also in shell -h, the command is called "annotations" which is currently "annotate".

**Comment by dereuromark** [comment]
True.
You could also help out and quickly make a PR here.

**Comment by dereuromark** [comment]
Done in master.

**Comment by alexdd55** [comment]
> 
> 
> True. This was a change toward command naming in 4.x.
> You could also help out and quickly make a PR here.

will do  next time.
