### ISSUE TITLE
Ignore templates in `Template/Bake`

### ISSUE THREAD

**Issue by JD-Robbs** [dereuromark/cakephp-ide-helper#20]
I **love** this! 😃 

As a slight improvement:  it would be great if this plugin had an option to ignore files inside `Bake` - since adding annotations leads to syntax errors.

**Comment by dereuromark** [comment]
Would you mind making a small PR with your Suggestion?

**Comment by dereuromark** [comment]
Also:
What exactly are the paths it runs into?
And what command did you run?

**Comment by JD-Robbs** [comment]
Essentially, I am running `annotations all` on a plugin which provides themeing to my app - layouts, helpers, view classes and a `Bake` template.

Now, thinking about it, perhaps it's best to move the `Bake` template into a separate plugin and simply exclude that plugin when running annotations.

This shell is such a great time saver - thanks! 👍

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-ide-helper/tree/master/docs#skipping-folders

**Comment by JD-Robbs** [comment]
That's strange.  Maybe it has to do with the fact that my `Bake` theme is inside a plugin and I run `annotations all` with the `-p MyTheme` option.  Perhaps `Bake` is only skipped if the templates are inside the main app?

**Comment by dereuromark** [comment]
No, I tested with my Setup plugin and it should work.
Please debug the path it has with the path you expect, and let me know, maybe we can make a small patch here that works for you as well.
