### ISSUE TITLE
Namespace-less annotations

### ISSUE THREAD

**Issue by andrii-pukhalevych** [dereuromark/cakephp-ide-helper#204]
Feature discussion:
Is it easy to not add namespace for properties that have classes from current namespace?

For example generate `@property User[] $user` instead of `@property \App\Model\Entity\User[] $user` for classes inside `App\Model\Entity`.

**Comment by dereuromark** [comment]
Whats the reason?
Docblock annotations should always be FQCN, having them depend on use statements is an anti pattern.

**Comment by andrii-pukhalevych** [comment]
For models, almost all object properties usually are from the same
namespace (except FrozenTime/Date)

**Comment by dereuromark** [comment]
If the tooling provides proper annotations, you shouldn't bother about this.
There are more important things to focus on IMO usually.

**Comment by andrii-pukhalevych** [comment]
Yeah. For me its more visually clear without namespaces. I guess I'm just used to it.

**Comment by dereuromark** [comment]
Yeah :)
