### ISSUE TITLE
Missing annotate

### ISSUE THREAD

**Issue by LubosRemplik** [dereuromark/cakephp-ide-helper#208]
Maybe I am doing something wrong, but `bin/cake annotate all -p Admin` did not created highlighted annotations below

![image](https://user-images.githubusercontent.com/556169/89655118-e9289b00-d8c9-11ea-9880-0e59ca7f28df.png)

And those are basic cakephp components, any idea why?

Great plugin, looking forward to use it fully

**Comment by dereuromark** [comment]
Arent they on core one already?

**Comment by LubosRemplik** [comment]
`@property \Cake\Controller\Component\FlashComponent $Flash` is at `Cake\Controller\Controller`, but `Security` and `Auth` is not

**Comment by dereuromark** [comment]
And they are also not a parent one? Like AppController etc?

**Comment by LubosRemplik** [comment]
Nope, app skeleton `AppController` does not have those

https://github.com/cakephp/app/blob/master/src/Controller/AppController.php

**Comment by dereuromark** [comment]
Whats the namespace of your file/class?
Can you debug it and see what classes it finds in the annotator? Maybe that reveals sth.

**Comment by dereuromark** [comment]
I found the reason why: Prefixed controllers arent fully supported in 3.x yet
I think 4.x here is fine, but in 3.x one

    $className = App::className(($plugin ? $plugin . '.' : '') . $controllerName, 'Controller');

always returns false for prefix ones.

Do you want to make a PR here?

**Comment by dereuromark** [comment]
It actually wasnt that hard to backport: https://github.com/dereuromark/cakephp-ide-helper/commit/dfd2edac44c4861b5f08570599e97a62cf4278e5
Can you check if the latest dev-cake3 works here?

**Comment by LubosRemplik** [comment]
Sorry to not describe on the beggining, I am having isue with 4.x version and cant try dev-cake3 at the project I am testing because there is installation conflict with bake

> Whats the namespace of your file/class?
> Can you debug it and see what classes it finds in the annotator? Maybe that reveals sth.

```
namespace Admin\Controller

class AdminController extends \Cake\Controller\Controller
```

I think rule you have at `Annotator/ControllerAnnotator.php`, `getComponentAnnotations`, line 130 is wrong. You are skipping all `Cake` component assumming they are loaded in `Cake\Controller\Controller` or in `AppController` but cake loads only e.g. `FlashComponent` or `PaginatorComponent` but let you load yourself some components e.g. `SecurityComponent` or `AuthComponent` by yourself that's why this rule skipping `Cake` vendor might be wrong

What you think?

**Comment by dereuromark** [comment]
OK, you might be right here. But could this also be a core issue?
Maybe the core should annotate those directly in Cake\Controller\Controller?

**Comment by LubosRemplik** [comment]
Yep, maybe should be annotated in core - worth to open question/issue at cake/cake? or you think OK to do PR to remove this few lines which are skipping the Cake vendor annotates generation?

**Comment by dereuromark** [comment]
Those are deprecated, thats probably why.
Auth and Security
but IMO they should still be in that list until fully removed.

**Comment by LubosRemplik** [comment]
You are right and thanks for opening PR, we can close this
