### ISSUE TITLE
Upgrade of depency sebastian diff rom 3 to 4 for phpunit upgrade

### ISSUE THREAD

**Issue by bebna** [dereuromark/cakephp-ide-helper#214]
Hi,

it looks like this extension is currently blocking cake 4 setups from using phpunit 9, because of the usage of `sebastian/diff ^3.0.0` in the compose.json . I don't have the overview myself currently about the changes between diff 3 and 4, would that be a big problem?

**Comment by dereuromark** [comment]
I think you can make a PR to allow also v4.
The API of it shouldn't change, it is probably mainly about PHP8 and typehints.

**Comment by dereuromark** [comment]
See https://github.com/dereuromark/cakephp-dto/commit/5ad8a7c88c9f7e4817bfe0ec54fb2e826d359751

**Comment by dereuromark** [comment]
Part of https://github.com/dereuromark/cakephp-ide-helper/releases/tag/1.8.1
