### ISSUE TITLE
PhpStorm autocomplete problem

### ISSUE THREAD

**Issue by mcube27** [dereuromark/cakephp-ide-helper#217]
Hi,

I am using Cakephp 4 and cakephp-ide-helper 1.8.0.

Since I installed it, Phpstorm autocomplete had issues showing me function from `PHPUnit\Framework\TestCase` as it looks like there is the same one in cakephp-ide-helper and it conflicts with it.

As it's supposed to help the ide, it's a bit annoying :)

Thank you for your help

**Comment by dereuromark** [comment]
Can you be a bit more specific? What kind of file are you referring to?
Whats the exact issue?
I dont see such a file in the repo nor do I see the current conflict for the project.

**Comment by mcube27** [comment]
For what I could see, this file is the one causing the problem :
`vendor/dereuromark/cakephp-ide-helper/tests/TestCase.php`

I am running an integration test which extends `Cake\TestSuite\TestCase` which extends `PHPUnit\Framework\TestCase` but then PhpStorm has to choose between your file and PhpUnit file.

Then when I want to get autocomplete for $this->expectException(), PhpStorm does not find it if he looks in your file, as it's empty.

I hope it's more specific, I am no expert. However, I removed cakephp-ide-helper and PhpStorm worked as expected and can autocomplete the function.

**Comment by dereuromark** [comment]
I see.
I guess we could remove that file from the tag.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-ide-helper/commit/f275bf018c850d40015cc1b4d38206608a8f33d3
Once I release the next patch this will then be resolved.

**Comment by mcube27** [comment]
thank you for your fast reaction !!
