### ISSUE TITLE
Cross issue : Netbeans 

### ISSUE THREAD

**Issue by HumanG33k** [dereuromark/cakephp-ide-helper#226]
I do not know if it make sense but this helper probably also be use with netbeans.

There is already a a cakephp addon for netbeans i will cross reference issues.
https://github.com/cakephp/cakephp-netbeans old one.
and more uptodate :
https://github.com/junichi11 -> https://github.com/junichi11/cakephp3-netbeans/issues/73  (repo is for cake3 AND cake 4)

**Comment by dereuromark** [comment]
You can add the info into wiki

**Comment by HumanG33k** [comment]
@dereuromark of course which one ?

**Comment by dereuromark** [comment]
You can create a new page in https://github.com/dereuromark/cakephp-ide-helper/wiki and link it there in the overview list.

**Comment by dereuromark** [comment]
Docs can be updated here, including wiki
