### ISSUE TITLE
Illuminator: problem with directory separator and preg_match in Windows

### ISSUE THREAD

**Issue by hacheraw** [dereuromark/cakephp-ide-helper#228]
When I try to run Illuminator on Windows 10, it does nothing.
Here is a screenshot (I ran it a second time with `-v`
![windows](https://user-images.githubusercontent.com/10481749/109557564-2eafee00-7ad0-11eb-93b4-870d06faa017.png)

It seems like the Directory Separator or something is breaking things...

In Linux, same project works fine:
![linux](https://user-images.githubusercontent.com/10481749/109557653-47b89f00-7ad0-11eb-8180-104194c5f32f.png)

I tried different shells (WSL, GIT Bash, PowerShell and cmd)

----

**I made some test before submiting the issue and found what is happening.**

```php
public function shouldRun(string $path): bool {
		return (bool)preg_match('#/Model/Entity/.+\\.php$#', $path);
	}
```

This function was always return `false`.

I managed to solved changing the regex to this one:

```php
return (bool)preg_match('#' . preg_quote(DS) . 'Model' . preg_quote(DS) . 'Entity' . preg_quote(DS) . '.+\\.php$#', $path);
```

It might not be the best approach tho...

![image](https://user-images.githubusercontent.com/10481749/109562214-00cda800-7ad6-11eb-89b0-d83d14530de0.png)

**Changing that, it just works as expected in both Windows and Linux**. Said that...

I also found this line:

```php
public function illuminate($path = null) {
    if (!$path) {
        $path = 'src/';
    }
```

While it still passes the regex and PHP auto converts `/` to the correct one in Windows, it may be a good idea to change it to

```
'src' . DS
```

----

**If you are OK with my approach, I'd be glad to open a PR. In that case, tell me if you want me to include the second (optional) change**

**Comment by dereuromark** [comment]
I am looking forward to the fix for Win compatibility, including both changes.
