### ISSUE TITLE
Generate Template docblock also for Forms

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-ide-helper#23]
```php
//in action
$documentationForm = new DocumentationForm();
$this->set(compact('documentationForm'));

// in template ctp
<?= $this->Form->create($documentationForm) ?>
```

maybe?

Form suffix is needed here then.

**Comment by dereuromark** [comment]
How would this look like?
Parsing the "specific" controller actions for a template could be difficult to do.
But only then you would you that this action provides a form here - unless you call the variable `$documentationForm` by convention :)

**Comment by PhantomWatson** [comment]
It seems like this could be generalized into "add doc comments for any variable set by `$this->set()` in the controller".

**Comment by dereuromark** [comment]
Dont think we know the types then, though.

**Comment by dereuromark** [comment]
We could use the convention to have the type suffixed:

```php
// in template ctp
<?= $this->Form->create($documentationForm) ?>
```
That might help, but would still be rather fuzzy.
