### ISSUE TITLE
Allow using --ci flag on individual annotators

### ISSUE THREAD

**Issue by ekisu** [dereuromark/cakephp-ide-helper#230]
It would be really nice to be able to do something similar to this, so that one does not need to enforce all annotation types during CI runs:
```
bin/cake annotate models -v -d --ci
bin/cake annotate controllers -v -d --ci
```

**Comment by dereuromark** [comment]
Do u want to make a Pr?

**Comment by ekisu** [comment]
Sure, made a PR
