### ISSUE TITLE
Entity field annotations.

### ISSUE THREAD

**Issue by andrii-pukhalevych** [dereuromark/cakephp-ide-helper#232]
Hi @dereuromark 

Im thinking long time about entity field annotations, and have some idea for 2030 year:

what if field names will be stored inside entity constants?

```
class User {
    const FIELD_ID = 'id';
    const FIELD_USERNAME = 'username';
}

```
It will be possible to use that when writing queries, forms etc.

`$this->loadModel(UsersTable::class)->find()->select([User::FIELD_ID, User::FIELD_USERNAME])->first();`

```
$this->Form->control(User::FIELD_ID);
$this->Form->control(User::FIELD_USERNAME);
```

And also add return types via `.ide-helper.meta`

Constants will be possible to use in validation and other places, so navigation will be really easy.

I know that its absolutely another way comparing to php doc blocks, but sounds also not bad.

**Comment by dereuromark** [comment]
Did u check docs on illuminator?^^

**Comment by andrii-pukhalevych** [comment]
No, never hear about it.
So thanks a lot for suggesting :)

Will try to use that
