### ISSUE TITLE
How can I use cake-ide-helper with  Intelephense Extension in VSC

### ISSUE THREAD

**Issue by nicokaiser79** [dereuromark/cakephp-ide-helper#233]
I try to use the cake-ide-helper with the  Intelephense Extension in VSC.
I installed cake-ide-helper with composer in the dev environment and added it to the application as addPlugin ($this->addPlugin('IdeHelper');). 
For Excample i load a component in a conmtroller

$this->loadComponent('MyComponent');

But there no completion for when I try $this->MyComponent?

What can i do the the CodeComplettion shown in VSC. In Netbeans will be automatically shown.

**Comment by raul338** [comment]
Run
```
bin/cake annotate all
bin/cake phpstorm generate
```

I never used this yet, but could help:
```
bin/cake code_completion generate
```

See the [usage](https://github.com/dereuromark/cakephp-ide-helper/tree/master/docs) docs

**Comment by dereuromark** [comment]
Make sure then to add your experiences and recommendations into a wiki page for that IDE:
https://github.com/dereuromark/cakephp-ide-helper/wiki#recommended-ide-settings

**Comment by nicokaiser79** [comment]
I have the ide-helper by this instruction https://github.com/dereuromark/cakephp-ide-helper/tree/master/docs.
But when I run  bin/cake annotate all will be "Unknown command `cake annotate`. Run `cake --help` to get the list of commands." shown. 

The Command "bin/cake plugin loaded" bring that
Authentication
Bake
Cake/TwigView 
DebugKit      
IdeHelper     
Migrations    

But the command "bin/cake --help" bring that
Current Paths:

* app:  src\
* root: D:\dev\shop\
* core: D:\dev\shop\vendor\cakephp\cakephp\

Available Commands:

App:
 - console
 - help

Bake:
 - bake
 - bake all
 - bake behavior
 - bake cell
 - bake command
 - bake component
 - bake controller
 - bake controller all
 - bake fixture
 - bake fixture all
 - bake form
 - bake helper
 - bake mailer
 - bake middleware
 - bake model
 - bake model all
 - bake plugin
 - bake shell
 - bake shell_helper
 - bake task
 - bake template
 - bake template all
 - bake test

Cake/TwigView:
 - twig-view compile

CakePHP:
 - cache clear
 - cache clear_all
 - cache list
 - completion
 - i18n
 - i18n extract
 - i18n init
 - plugin assets copy
 - plugin assets remove
 - plugin assets symlink
 - plugin load
 - plugin loaded
 - plugin unload
 - routes
 - routes check
 - routes generate
 - schema_cache build
 - schema_cache clear
 - server
 - version

DebugKit:
 - benchmark

Migrations:
 - bake migration
 - bake migration_diff
 - bake migration_snapshot
 - bake seed
 - bake simple_migration
 - migrations
 - migrations create
 - migrations dump
 - migrations mark_migrated
 - migrations migrate
 - migrations orm-cache-build
 - migrations orm-cache-clear
 - migrations rollback
 - migrations seed
 - migrations status

To run a command, type `cake command_name [args|options]`
To get help on a specific command, type `cake command_name --help`
