### ISSUE TITLE
annotate() respect application namespace

### ISSUE THREAD

**Issue by tbelknapsgs** [dereuromark/cakephp-ide-helper#243]
Following up on someone else's hard work, but here is a link to the problem:
https://github.com/dereuromark/cakephp-ide-helper/blob/1.14.0/src/Annotator/ComponentAnnotator.php#L42-L44

That should respect the actual application namespace instead of using the default.

Thanks! 

I'm sorry, I don't see a set of instructions for submitting a bug report, so no template. But this is Cake4.2.

**Comment by dereuromark** [comment]
Is someone able to make one here? @challgren or alike?

**Comment by dereuromark** [comment]
Can you check if https://github.com/dereuromark/cakephp-ide-helper/pull/244 solves it?

**Comment by tbelknapsgs** [comment]
I've installed via Composer, so can't checkout the feature branch, sorry!

**Comment by dereuromark** [comment]
You can use dev Master aliasing

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-ide-helper/releases/tag/1.14.1

**Comment by tbelknapsgs** [comment]
Fix confirmed, thank you very much!
