### ISSUE TITLE
Method with same name already defined in this class

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-ide-helper#255]
I am using the 1.15.0 version of the ide-helper plugin and enabled `arrayAsGenerics` support in my config.

```
  'IdeHelper' => [
    'arrayAsGenerics' => true
  ]
```

Now when I re-do the annoations PHPStorm seems to not like the new array annotations.

![image](https://user-images.githubusercontent.com/9105243/140587264-fd76f833-415d-458f-84ae-92234fba2288.png)

Is this a PHPStorm issue?

**Comment by dereuromark** [comment]
See https://twitter.com/dereuromark/status/1455496522049728517

Nothing we can do at this point than upvoting and making sure with more pressure they fix their IDE
Until then you can ignore it, as it seems to still somehow partially work, or use the current config (default) of not using this syntax - which also means you need to make sure the CS ruleset ignores method annotations.

**Comment by LordSimal** [comment]
thanks, I knew I have seen that somewhere but didn't look into twitter ^^
already upvoted that issue 👍

**Comment by dereuromark** [comment]
That said, I think I must have missed some, as the last ones are still old syntax:
 ```php
 * @method \App\Model\Entity\ReleaseGroup[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\ReleaseGroup[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\ReleaseGroup[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 ```
 
 If you have time and want to look into that, would be greatly appreciated.

**Comment by dereuromark** [comment]
Never mind, those are supposed to stay as they are not simple generics, but collection object.
