### ISSUE TITLE
Smart sorting for new doc block properties and methods

### ISSUE THREAD

**Issue by andrii-pukhalevych** [dereuromark/cakephp-ide-helper#267]
Enhancement idea:

When adding new properties or methods into doc block, try to find if there is sibling property is already added and add new property below instead of adding at the bottom of the doc block.

Example: if line for `save(\Cake\Datasource\EntityInterface $entity, $options = [])` already exists in table doc block, then add `saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])` below save.

Or if entity property $id already exists in entity doc block, then add new property $email below $id, not at the bottom of the doc block to keep things close.

**Comment by dereuromark** [comment]
You can sure try to do this.
Usually I dont bother since a code sniffer rule here takes care of the cleanup and sorting.
