### ISSUE TITLE
Annotations are added before `declare(strict_types=1);` causing syntax errors in .ctp file

### ISSUE THREAD

**Issue by Spriz** [dereuromark/cakephp-ide-helper#269]
Hi! First of all - thanks for a super awesome tool!

I have a file `src/Template/Element/Offers/html.ctp` that has this start:

```php
<?php declare(strict_types=1);

use App\Utility\ApactaS3CloudStorage;
use Cake\I18n\Number;
use App\Model\Entity\Offer;

/**
 * @var \Companies\View\AppView $this
 * @var \App\Model\Entity\Company $company
 * @var \App\Model\Entity\User $user
 * @var \App\Model\Entity\Offer $offer
 * @var float $totalSalesPrice
 */
?>
```

After running `bin/cake annotations all` the file looks like this:

```php
<?php
/**
 * @var \App\View\AppView $this
 * @var mixed $totalSalesPrice
 * @var \App\Model\Entity\Offer $offer
 * @var \App\Model\Entity\Company $company
 */
?>
<?php declare(strict_types=1);

use App\Utility\ApactaS3CloudStorage;
use Cake\I18n\Number;
use App\Model\Entity\Offer;

/**
 * @var \Companies\View\AppView $this
 * @var \App\Model\Entity\Company $company
 * @var \App\Model\Entity\User $user
 * @var \App\Model\Entity\Offer $offer
 * @var float $totalSalesPrice
 */
?>
```

Which now causes a syntax error with `php -l src/Template/Element/Offers/html.ctp`:

```
php -l src/Template/Element/Offers/html.ctp
PHP Fatal error:  strict_types declaration must be the very first statement in the script in src/Template/Element/Offers/html.ctp on line 9
Errors parsing src/Template/Element/Offers/html.ctp
```

**Comment by Spriz** [comment]
Oh, and we're on cake3 with cakephp-ide-helper on `0.14.10`

**Comment by dereuromark** [comment]
Feel free to provide a PR for the outdated Version that Puts docblocks after strict tag

**Comment by Spriz** [comment]
@dereuromark I'll just close this one :v: I just spent a few minutes in the source code but didn't spot where to start and we're moving towards cake4 anyway as well :v:

**Comment by dereuromark** [comment]
Is the same issue present there?

**Comment by dereuromark** [comment]
I added a test that shows that your issue is also present in master.
If someone finds a way to offset the php open tag index to the last of that declare() line, probably the `;`
Then maybe we can find a way to support them - to always declare docblocks after that line

**Comment by dereuromark** [comment]
You could try to backport my fix in https://github.com/dereuromark/cakephp-ide-helper/pull/270 and see it that works for you.
