### ISSUE TITLE
Template annotations get duplicated

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-ide-helper#276]
I got a pretty weird problem regarding the `bin/cake annotate all` feature.

On certain (not all) template files the PHPDoc at the start of the file gets duplicated even though the code is already present.

<img width="965" alt="image" src="https://user-images.githubusercontent.com/9105243/180317347-5126f5a4-ed52-49db-b622-63d143842e4f.png">

If you want I can provide that exact file

I am on version 1.17.1

**Comment by dereuromark** [comment]
Can you reproduce this with a test case inside this plugin?
I wonder if this could be related to the whitespace used, or newline style used, or the inline docblock below maybe confusing the tool?

**Comment by dereuromark** [comment]
Please also check latest master as some improvements have been added regarding docblock parsing.

**Comment by dereuromark** [comment]
I think we should handle, and should be able to do so, the issue here.

**Comment by dereuromark** [comment]
Check `testAnnotateInline` test, as this one should still work
I guess we have to check for additional whitespace after a docblock, e.g.
```
/** @var Authorization\Identity $identity */
$identity = $this->getRequest()
```
vs
```
/** @var Authorization\Identity $identity */

$identity = $this->getRequest()
```
The latter would count as what we want, whereas the first is clearly an inline docblock for the line afterwards.

**Comment by dereuromark** [comment]
I was able to reproduce in https://github.com/dereuromark/cakephp-ide-helper/compare/bugfix/following-inline
If you find a way, feel free to use my branch as base.

**Comment by dereuromark** [comment]
Should be fixed with https://github.com/dereuromark/cakephp-ide-helper/pull/277

**Comment by LordSimal** [comment]
I can confirm, that the current master branch fixes this issue

**Comment by dereuromark** [comment]
Released as https://github.com/dereuromark/cakephp-ide-helper/releases/tag/1.18.1
