### ISSUE TITLE
Add phpstan/phpdoc-parser to composer.json

### ISSUE THREAD

**Issue by andrii-pukhalevych** [dereuromark/cakephp-ide-helper#279]
https://github.com/dereuromark/cakephp-ide-helper/blob/d5d8956a9b58902577cfca932d9fdc1582a58672/src/Annotator/Traits/DocBlockTrait.php#L11-L23

Doesn't it needed to add `"phpstan/phpdoc-parser"` in `composer.json`?

**Comment by dereuromark** [comment]
Afaik, the sniffer package we include already adds this as indirect dependency
So as long as there is no significant risk on the BC topic regarding this, I guess we dont necessarily need to include it directly.

**Comment by andrii-pukhalevych** [comment]
I installed manually via composer.json therefore it didn't work with error message `Class 'PHPStan\PhpDocParser\Parser\ConstExprParser' not found`. But it's ok, I already added "phpstan/phpdoc-parser" to my project.
