### ISSUE TITLE
Discussion: Add column names as constants to table class

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-ide-helper#280]
I am currently working in a project where the team introduced the idea of adding column constants to the table class so one can easily reference columns in the codebase. This also helps identifiying places where a specific column is being used in the codebase when e.g. a column is being renamed to adjust `->where()` queries.

We used a naming scheme like `C_COL_FIRSTNAME` for e.g. a column called `firstname`

This would change the look of a `->where()` from
```
$query->where(['StaffMembers.firstname' => 'Kevin']);
```
to
```
$query->where([StaffMembers::C_COL_FIRSTNAME => 'Kevin']);
```

or basically anywhere else where the default table aliases are used.

This of course doesn't work if one builds a query which has custom aliases set.

What is your opinion about that? Is it a good idea?
Do we want to add this kind of feature to the IDE Helper (maybe as an optional flag)

**Comment by dereuromark** [comment]
This does already exist on the entity level, see Illumitator tasks and how to make the fields exposed as constants.

**Comment by LordSimal** [comment]
I am blind, sorry 😅
