### ISSUE TITLE
Annotate @route for entry points

### ISSUE THREAD

**Issue by jarovarga** [dereuromark/cakephp-ide-helper#283]
```
/**
 * @route /users
 */
class UserController extends AppController {
```
It might be super useful to have the entry point annotated here and add `@route` to suppressed annotations instead of setting up every class and method in entry points config or annotate with `@uses`...

**Comment by dereuromark** [comment]
How would that look like code wise for the annotator?

**Comment by jarovarga** [comment]
The annotator has no restrictions on the use of custom annotations.

It’s very frustrating suppress unused controllers and methods because they are the entry points.

And nowhere isn’t simple and quick solutions…

**Comment by dereuromark** [comment]
Feel free to make a PR
