### ISSUE TITLE
Autocomplete URL arrays

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-ide-helper#287]
It would be nice to have autocomplete for parts of the URL array used in e.g.
```
$this->Html->link('Title', [
    'controller' => 'MyControler',
    'action' => 'myAction',
    'plugin' => 'MyPlugin'
]);
```
which is also used in other places like inside tests for `$this->get()`

**Comment by dereuromark** [comment]
You have that using IDE PHPStorm plugin DeepAssoc as per docs
https://github.com/dereuromark/cakephp-ide-helper/wiki/PHPStorm

**Comment by LordSimal** [comment]
This indeed is pretty cool for the array-key part, but what I am talking about is the value behind the key.
So like the value behind the key 
* `controllers` should have autocomplete of all available controllers
* `action` should have autocomplete of all available acitons inside the selected controller

Something like we have for `$this->fetchTable('')`
![image](https://user-images.githubusercontent.com/9105243/191499152-4640d2a2-4b16-4820-9c6a-b00ed3763dd7.png)

**Comment by dereuromark** [comment]
Is that even possible with the current func?
Or is this rather sth a PHPStorm plugin would need to be written
In that case we have to close this here.

**Comment by LordSimal** [comment]
I thought this was possible but maybe I am mixing things up here. In that case I will close this.
