### ISSUE TITLE
Newly generated model events use not correct return types

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-ide-helper#288]
The feature added in #284 now produces the following error in PHPStorm:
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/9105243/193654256-54482585-3390-4884-8c8f-9e6c62d91159.png">

The first error can be adjusted on my side, because my 2nd param can easily be adjusted to `EntityInterface`.

But the second error regarding the return type is wrong because `beforeSave()` definitely is not a `void` hook as you can see in https://github.com/cakephp/cakephp/blob/4.x/src/ORM/Table.php#L1943

The event data is definitely used and therefore the return type needs to be adjusted here.

**Comment by dereuromark** [comment]
Do u want to make a PR here?

**Comment by LordSimal** [comment]
So it is recommend to set the result on the event like `$event->setResult(false);` instead of returning... got it

**Comment by dereuromark** [comment]
I believe it is to stop the propagation of the event. But I am fine either way.

**Comment by LordSimal** [comment]
well at least the documentation states:
`In order to stop events you can either return false in your callbacks or call the stopPropagation() method on the event object:`
https://book.cakephp.org/4/en/core-libraries/events.html#stopping-events

**Comment by dereuromark** [comment]
Which - I would argue - is mainly for legacy reasons also including the return type :)

**Comment by dereuromark** [comment]
I opened https://github.com/cakephp/cakephp/issues/16786 for discussion, as I am not sure why we keep this the old ways around (except for easier upgradability coming from older majors).

**Comment by dereuromark** [comment]
With https://github.com/dereuromark/cakephp-ide-helper/releases/tag/1.18.4 I fixed a few more signatures to the "expected" default way.
Should we just close this then as those are the common way of doing things for new callbacks?
It would be easy enough to adjust the return type if you really have to do things differently. But the ones generated should be best practice IMO.
