### ISSUE TITLE
Auto-generated @method annotations create psalm error

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-ide-helper#291]
After auto-generating all annotations for controllers and models I get the following error in psalm 4.29 with errorLevel 3

```
ERROR: TooManyTemplateParams - plugins/AlfredProjects/src/Controller/ProjectStatisticEntriesController.php:24:36 - Cake\Datasource\ResultSetInterface<AlfredProjects\Model\Entity\ProjectStatisticEntry> has too many template params, expecting 0 (see https://psalm.dev/184)
        $projectStatisticEntries = $this->paginate($this->ProjectStatisticEntries);


ERROR: TooManyTemplateParams - src/Controller/CategoriesController.php:347:9 - Cake\Datasource\ResultSetInterface<App\Model\Entity\Category> has too many template params, expecting 0 (see https://psalm.dev/184)
        $this->Categories->deleteMany($emptyModules);
```

As you see this is present for the `paginate()` annotation
```
 * @method \Cake\Datasource\ResultSetInterface<\AlfredProjects\Model\Entity\ProjectStatisticEntry> paginate($object = null, array $settings = [])
```
as well as the `deleteMany()` annotation
```
 * @method \Cake\Datasource\ResultSetInterface<\App\Model\Entity\Category>|false deleteMany(iterable $entities, $options = [])
```
inside the TableClass

Or could this be a problem with psalm?

**Comment by dereuromark** [comment]
What does too many template params mean here?
I am not too familiar with psalm and the issue it outlines here.

Afaik those annotations are "correct" as to what they return and what the IDE needs to know in order to be able to iterate over them.

**Comment by LordSimal** [comment]
Looking at https://github.com/vimeo/psalm/issues/5745 it seems that `\Cake\Datasource\ResultSetInterface` has to declare that it can have a template param (which it currently doenst)

**Comment by LordSimal** [comment]
Adding `@template T` to the ResultSetInterface indeed fixes this problem

**Comment by dereuromark** [comment]
So is that a core issue?

**Comment by LordSimal** [comment]
I will create a PR, in there we can discuss
