### ISSUE TITLE
Invalid line in CodeCompletionCakeORM.php triggers Phpstorm's inspection

### ISSUE THREAD

**Issue by asgraf** [dereuromark/cakephp-ide-helper#293]
code completion generates `tmp/CodeCompletionCakeORM.php` that contains following line:
```php
public function buildRules(EventInterface $event, RulesChecker $rules): RulesChecker {}
```
This is incompatible with \Cake\ORM\Table implementation:
```php
public function buildRules(RulesChecker $rules): RulesChecker
{
    return $rules;
}
```
This mismatch triggers Phpstorm's `Parameter's name changed during inheritance` inspection on every Table class
```
Parameter's name changed from 'event' to 'rules'
```

**Comment by dereuromark** [comment]
The IDE should not introspect those tmp files for inspection IMO
Is there a way to remove that?

Otherwise you might want to make a PR to return $rules here in the code, might be best.

**Comment by asgraf** [comment]
Problem is not in return value but in a number of function arguments

**Comment by dereuromark** [comment]
Now I see, buildValidator() has EventInterface as first param, but buildRules() does not

**Comment by dereuromark** [comment]
Can you check if https://github.com/dereuromark/cakephp-ide-helper/commit/16345c400e2af0395a2463e179d5c55f36ad4543 in master fixes it?

**Comment by asgraf** [comment]
Im confirming that https://github.com/dereuromark/cakephp-ide-helper/commit/16345c400e2af0395a2463e179d5c55f36ad4543 fixed the issue
