### ISSUE TITLE
Use of an alternative datasource file

### ISSUE THREAD

**Issue by wp4nuv** [dereuromark/cakephp-ide-helper#300]
Our CakePHP 3 (helper version 0.14*) project was architected in a way that separates configuration based on domains (mydomain.com), for example.  It's in that folder that the datasources.php file exists. `app.php` has been modified to read from this folder before parsing the rest of the file.  Right now, `phpstorm generate` only reads the datasources section of app.php.
Temporarily editing `app.php` does the trick.  Is the helper parsing `app.php` completely or going straight for the datasources section therein?

**Comment by dereuromark** [comment]
The Code usually contains the answers:
https://github.com/dereuromark/cakephp-ide-helper/blob/ef4afe6de8f600dc41c2d9afb1402686ca3b6449/src/Generator/Task/ConfigureTask.php#L56

**Comment by wp4nuv** [comment]
I think the fact the IdeHelper is not an httpd request, then any special config sections won't be read and the Helper defaults everything to `app.php`.  Our special configuration read assumes the `$_SERVER` variable is set which is not for these cli runs. Thank you!  I appreciate your work!

**Comment by wp4nuv** [comment]
A note to others, the ConfigureTask.php that Mark cites is for the master branch which doesn't apply to the cake3 version of the ide-helper.

**Comment by dereuromark** [comment]
Someone could have backported it maybe.
But yeah.
