### ISSUE TITLE
[Feature request] config autocompletion 

### ISSUE THREAD

**Issue by umer936** [dereuromark/cakephp-ide-helper#307]
Autocomplete for `app_local.php`

In many plugins, eg. cakephp/queue, dereuromark/cakephp-queue, etc, there are parameters to add to your `app_local.php`.
Rather than looking at the docs each time, it would be nice if there were annotations that could be read by ide-helper. 

For example, in a plugin of my own, you need to define large parameter arrays and being able to autocomplete the options would be helpful.

**Comment by dereuromark** [comment]
That cannot be made possible using the CakePHP plugin I am afraid
I dont see how it could be done using the IDE this way.
You would need to code an IDE plugin natively.

**Comment by umer936** [comment]
Tried for a bit yesterday. Yeah, I don't see how it can be done without JetBrains adding feature to the .phpstorm.meta functionality. 

Feel free to close the issue or leave it open if there becomes a way to do it.
