### ISSUE TITLE
Composer setup script : Is there a problem about return types for some functions in Controller ?

### ISSUE THREAD

**Issue by bouillerot** [dereuromark/cakephp-ide-helper#310]
## in vendor/cakephp/cakephp/src/Controller/Controller.php

```
/**
 * Called before the controller action. You can use this method to configure and customize components
 * or perform logic that needs to happen before each controller action.
 *
 * @param \Cake\Event\EventInterface $event An Event instance
 * @return \Cake\Http\Response|null|void
 * @link https://book.cakephp.org/4/en/controllers.html#request-life-cycle-callbacks
 */

public function beforeFilter(EventInterface $event)
    {
    }
```
### in tmp/CodeCompletionCakeController.php

```

...

abstract class Controller {
    public function startup(EventInterface $event): ?Response {
        return null;
    }
    public function beforeFilter(EventInterface $event): ?Response  {
        return null;
    }

...
```

- The void type is missing as a possibility to return void.
- Why these intermediate declarations are returning null instead of being empty as in Controller class ?

### So in src/Controller/AppController.php

I get a message 

Method 'App\Controller\AppController::beforeFilter()' is not compatible with method 'Cake\Controller\Controller::beforeFilter()'.intelephense(1038)

```
/**
 * Called before the controller action. You can use this method to configure and customize components
 * or perform logic that needs to happen before each controller action.
 *
 * @param \Cake\Event\EventInterface $event -
 * @return \Cake\Http\Response|null|void
 */
public function beforeFilter(EventInterface $event) 
{
    parent::beforeFilter($event);
    // dd($event->getData());
    /**
     * Every view will have
     * - the logged in user
     * - a flag to know, if impersonating mode is on
     */
    $loggedInUser = $this->getLoggedInUserAsUser($this->getLoggedInUser());
    $isImpersonating = $this->getIsImpersonatingMode();
    $this->set(compact('loggedInUser', 'isImpersonating'));
}
```

#### The fact is than in vendor/cakephp/cakephp/src/Controller/Controller.php 

**the function can return void** or "automagically" a Response

#### If I try to correct my code by adding  some return types

-  ```: ?|Response" ``` Still get the same message
-  ``` : null|Response|void``` I get the message "void cannot be used in that context."

## temporary solution I use, quick and dirty

I delete de return types in tmp/CodeCompletionCakeController.php and I'm no more annoyed, but have to delete again each time I run composer setup.

```
	abstract class Controller {
		public function startup(EventInterface $event) {
			return null;
		}
		public function beforeFilter(EventInterface $event) {
			return null;
		}
```

## Conclusion

Did I missed or misunderstood something ?
Any help will be appreciated

**Comment by dereuromark** [comment]
Well, it seems that many do not want to use direct return types in the controller code
So I removed it for now in https://github.com/dereuromark/cakephp-ide-helper/releases/tag/1.18.9

This should solve your issue.

**Comment by bouillerot** [comment]
# The symptom has disappeared, the patient is cured!

## Thank you for your diligence
