### ISSUE TITLE
Cake5: `fetchTable()` does not automatically result in a property

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-ide-helper#317]
Currently `bin/cake annotate controllers` will add 

```
@property \Queue\Model\Table\QueuedJobsTable $QueuedJobs
```

to the controller class phpdocs just if this is called.

```
$queuedJobsTable = $this->fetchTable('Queue.QueuedJobs');
```

But this should only happen if a property is actually set, not just a variable to hold the table instance.

**Comment by dereuromark** [comment]
Should be doable checking the line as a whole for

    $this->QueuedJobs = $this->fetchTable('Queue.QueuedJobs');

etc

**Comment by dereuromark** [comment]
I am fine with only supporting conventions out of the Box
If u deviate you can also write a custom task.
