### ISSUE TITLE
Annotate templates is adding phpdoc for variable even when it already exists

### ISSUE THREAD

**Issue by Harfusha** [dereuromark/cakephp-ide-helper#343]
![image](https://github.com/dereuromark/cakephp-ide-helper/assets/47174548/77c1ec3b-fee2-42db-9385-6206a70c34ef)

When variable have complex type like $args in screenshot then command `bin/cake annotate templates` is adding duplicated entry

**Comment by dereuromark** [comment]
Array shape isnt supperted yet afaik
Does anyone want to add Support for it?

**Comment by dereuromark** [comment]
Ah, look at that:
https://github.com/dereuromark/cakephp-ide-helper/pull/344/commits/587ea0dec2b86f25ce0404ae01193d53417e50d6
Adding a more complex type inside the shape and things start to fail..

So thats the part that isnt yet supported, primitive ones currently already work.

**Comment by dereuromark** [comment]
I fixed up the PR, please let me know if this fixes it for you.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-ide-helper/releases/tag/2.2.1
