### ISSUE TITLE
Complex type, that exists in property is added again

### ISSUE THREAD

**Issue by Harfusha** [dereuromark/cakephp-ide-helper#354]
I have this property on entity.
`@property array{user: int, account: string|null, newContacts: array<mixed>|null}|null $data`

When i run annotator same property is added again on the end.
`@property array|null $data`

![image](https://github.com/user-attachments/assets/9ee1c9d9-4768-4b2f-bef3-877c9c921495)

**Comment by dereuromark** [comment]
Cake5?

**Comment by Harfusha** [comment]
Cakephp 4

**Comment by dereuromark** [comment]
This is fixed in 5 afaik
You  an check if things can be backported

**Comment by Harfusha** [comment]
But it is already backported
https://github.com/dereuromark/cakephp-ide-helper/pull/348/commits/e212e9f9bdb0712edd5164b2522c4abddfa1ae5f

**Comment by dereuromark** [comment]
Whats the problem then? Any idea?

**Comment by dereuromark** [comment]
And does the same happen in 5.x?
Then it is maybe a phpstan Parser issue

**Comment by Harfusha** [comment]
Will try to write some tests next week for cake 4 and 5

**Comment by dereuromark** [comment]
Any update regarding this issue?

**Comment by Harfusha** [comment]
i had no time to do this. I hope i will find some time this week

**Comment by dereuromark** [comment]
$pieces = explode(' ', $tokens[$i + 2]['content']);

The Illuminator code uses basic explode() instead of more sophistacted phpstan docblock parsing
This would have to be ported from the annotator code it seems.
