### ISSUE TITLE
aren't annotations for Behaviors missing?

### ISSUE THREAD

**Issue by siran** [dereuromark/cakephp-ide-helper#39]
aren't annotations for Behaviors missing?

**Comment by dereuromark** [comment]
Please bei more specific. Do you have any code examples?

**Comment by siran** [comment]
I found strange the no annotations were made on the Behaviors. But I may have then misinterpreted the goal of this plugin...

**Comment by dereuromark** [comment]
What kind of annotations? They usually don't need any.

**Comment by siran** [comment]
I thought initially that this plugin could help PHPStorm identify methods defined in the Behavior and not in a Model, when hovering over the method name in a $Model->behavior_method().

**Comment by dereuromark** [comment]
That is already included, see ModelAnnotator and `@mixin` annotations.
