### ISSUE TITLE
Allow 3.0 of squizlabs/PHP_CodeSniffer

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-ide-helper#4]
Currently only works with 2.x version of that tool.

**Comment by dereuromark** [comment]
I started it here: https://github.com/dereuromark/cakephp-ide-helper/compare/develop
But it seems the autoloader of that tool doesnt really play nice with others, it cannot find those classes of the phpcssniffer.

**Comment by ewbarnard** [comment]
@dereuromark Mark, I'm finding that I first need to convert psr2r-sniffer to support PHP_CodeSniffer 3.x (composer dependency). I forked that project and I'm creating unit tests which extend their 3.x AbstractSniffUnitTest structure. I've gotten through the PSR2R/Sniffs/Classes section, with unit test(s) for each sniff and each sniff converted to PHP_CodeSniffer 3.x.

I'm figuring that dive into getting sniffer classes to load should tell me what I need for helping here (cakephp-ide-helper supporting sniffer 3.x).

**Comment by dereuromark** [comment]
There is also already a branch for it, slightly outdated. Together we should be able to get Things finished Up.

**Comment by ewbarnard** [comment]
@dereuromark I forked master for psr2r-sniffer, will that be a problem? I've not touched cakephp-ide-helper as yet, be happy to fork 'develop' rather than master.

**Comment by dereuromark** [comment]
Try Develop, yeah. Either way you can also use the cakephp sniffer for now to get this helper Working. Will make Things easier.

**Comment by ewbarnard** [comment]
@dereuromark Okay if I finish out the psr2r-sniffer first? It's useless only partly updated, of course. Tests should be helpful for future development.

**Comment by dereuromark** [comment]
Sure

**Comment by ewbarnard** [comment]
psr2r-sniffer conversion to support 3.x is about 80% complete. All sniffs receive unit tests as I convert them. I added to the docs explaining the testing structure. I hope to finish the conversion this week (in my fork of master). I don't have 100% coverage of all features targeted by each sniff, but it will now be easy to add sample code to the tests if I missed anything significant.

**Comment by ewbarnard** [comment]
Whew... got the psr2r-sniffer upgraded as a pull request. @dereuromark is the 'develop' branch sufficiently up-to-date for me to fork cake-ide-helper?

**Comment by dereuromark** [comment]
Nice!
No, I think that branch is rather outdated (  https://github.com/dereuromark/cakephp-ide-helper/pull/13/files ).
But you can copy paste over the changes that are useful.

**Comment by ewbarnard** [comment]
@dereuromark What branch do you prefer I fork for this issue (sniffer 3.x)? "develop" or "master" ?

**Comment by ewbarnard** [comment]
I missed converting Tools/Sniffer and Tokenizer. They have the same issue as cakephp-ide-helper, i.e., class PHP_CodeSniffer no longer exists. Working on it!

**Comment by dereuromark** [comment]
Thx!
You can either make a new PR for this repo, or built on the existing one here and make a PR against that one.

**Comment by ewbarnard** [comment]
Thanks @dereuromark ! I intend to make a new PR. I'm distracted by the U.S. holidays, could be as late as 8 July by time I get it ready.

**Comment by dereuromark** [comment]
@ewbarnard I started to add the autoloader so now it parses it correctly :)
We now just have to make the tests green and also make sure both phpcs v2 and v3 work without killing the other.

**Comment by dereuromark** [comment]
PR is now done and all works with 2.8 and 3.0 :)
