### ISSUE TITLE
Autocomplete for various loaders

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-ide-helper#45]
By adding them to phpstorm generator, you can autocomplete also those magic strings.

- [x] Helpers
```php
$this->loadHelper('TinyAuth.AuthUser');
$this->loadHelper('Meta.Meta', ['robots' => ['index' => true, 'follow' => true]]);
```

- [x] Components
```php
$this->loadComponent('Security');
```

- [x] Maybe Behaviors (but they return $this)
```php
$this->addBehavior('Tools.Jsonable');
```
---

- [x] Relations
```php
$this->hasMany('User');
$this->belongsTo('Company');
```
But does PluginName.ModelName syntax here work?  EDIT: Yes, it does.

**Comment by skie** [comment]
One note that could be useful for phpstorm helper. You can create folder ".phpstorm.meta.php" inside project and inside project possible to have many annotation files, like TableRegistry.meta.php Controller.meta.php

**Comment by dereuromark** [comment]
why would it be better to have separate files?
where do they have to be to be detected?

**Comment by skie** [comment]
Phpstorm process all files from this folder. In case you have features separately you can update some features without touching other files, like update only tables hinting or plugins. Also in this case users could have own custom hinting files that will not overwritten by phpstorm helper.

**Comment by dereuromark** [comment]
OK, so we should use a folder strategy here by default then?
Or would having the generic main file + folders (custom) on top work as well?

**Comment by dereuromark** [comment]
So for the plugin: `ROOT/.phpstorm.meta.php/.phpstorm.meta.php` as generated file.
Weird folder name, though..^^

And then people can have their
- `ROOT/.phpstorm.meta.php/Custom.meta.php`

on top
