### ISSUE TITLE
"Multiple definitions exist for class AppView"

### ISSUE THREAD

**Issue by andrej-griniuk** [dereuromark/cakephp-ide-helper#47]
Any way to avoid this?
![clipboard02](https://user-images.githubusercontent.com/2722793/30808257-097bcbdc-a206-11e7-8f3f-e6d362fdf715.jpg)

**Comment by dereuromark** [comment]
Sure, by not pulling the tests folder for ide-helper.
We should probably exclude this on https://github.com/dereuromark/cakephp-ide-helper/blob/master/.gitattributes then.

**Comment by dereuromark** [comment]
Should fix it in the next release: https://github.com/dereuromark/cakephp-ide-helper/commit/fd094212e093bd15ae5f859c15d73f8f67e8d435
