### ISSUE TITLE
`Multiple definitions exist for AppController` etc.

### ISSUE THREAD

**Issue by JD-Robbs** [dereuromark/cakephp-ide-helper#55]
IDE's including PHP Storm complain about multiple definitions of `AppController` inside the ide-helper's `test` dirs (`test_app` and `test_files`); the same happens with things like `AppView` and `AppHelper`.  I wonder if it would be possible to move the namespaces to something other than `App\Controller`, e.g. `IdeHelperApp\*Namespace*`?

I'd love to solve that with a simple rename/move-namespaces refactor in PHP Storm but don't really know how to then push that up here as I only ever push to private repos I have on BitBucket.

**Comment by dereuromark** [comment]
what release are you using?

**Comment by JD-Robbs** [comment]
Sorry buddy, I just did a `composer update` to `0.9.8` (I was on `0.9.6`) and everything looks just dandy. You work too fast! :)

**Comment by dereuromark** [comment]
;) Great to hear. Enjoy!
