### ISSUE TITLE
Muffin slug plugin 

### ISSUE THREAD

**Issue by davidyell** [dereuromark/cakephp-ide-helper#69]
I use the https://github.com/usemuffin/slug plugin in my project and when I was generating annotations the plugin wrote the docblock as the following.

```
* @mixin \Muffin\Slug.Slug
```

My PHP Storm didn't seem to like this and I had to replace it with the following.

```
* @mixin \Muffin\Slug\Model\Behavior\SlugBehavior
```

**Comment by dereuromark** [comment]
I kinda hoped you PRed the fix :)

**Comment by dereuromark** [comment]
What exactly is your addBehavior() statement?

**Comment by davidyell** [comment]
`$this->addBehavior('Muffin/Slug.Slug')` is what I have in my code. [As per the docs](https://github.com/usemuffin/slug#usage).

**Comment by dereuromark** [comment]
Resolved with https://github.com/dereuromark/cakephp-ide-helper/commit/5b0ae78d792a6040078662f18875faeb9e344aea

You really hit the one edge case right after releasing it :) nice one
