### ISSUE TITLE
Fixing template annotations corrupts binary files

### ISSUE THREAD

**Issue by dmromanov** [dereuromark/cakephp-ide-helper#90]
I have several binary files stored in `src/Template` folder. The files are used for generating a PDF file. They are: a `tiff` image used as a template, `png` logotype and a company font.

Fixing application annotations with `./bin/cake annotations templates` or `./bin/cake annotations templates` command corrupts these files.

I suggest fix only files that have an extension from a whitelist.

**Comment by dereuromark** [comment]
That's a good idea.
Do you want to help here?

**Comment by dereuromark** [comment]
Can you please check if https://github.com/dereuromark/cakephp-ide-helper/pull/91 solves the issue?

**Comment by dmromanov** [comment]
Thank you. It works.
